# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc809d9ffed4db27c15f19a6f2f6898b004088100ca1d5d5f78697eff77dff5198390097141252b5f8f2412db25994898915f04efdeebf15be943d69772328f1

test:
  secret_key_base: f8d059bdc90b931c8fcac96b45073ce60a163e485da39aac17dc3b4350c89b48238836988fee43fef550d62abeb56677bc6f659f511cd887d64a3df2a464ff5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
